# Generated by Django 3.2.7 on 2022-01-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220128_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='productprice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
